"""Shared constants for the headless garden simulation engine."""

BASE_TICK_HZ = 1
BASE_TICK_SECONDS = 1.0
MIN_ELAPSED_SECONDS = 0.0
DEFAULT_ENGINE_SYNC_INTERVAL_TICKS = 60
DEFAULT_CATCHUP_CHUNK_TICKS = 500
EPSILON_WATER = 0.01

DEFAULT_HOSE_CAPACITY = 10.0
DEFAULT_HOSE_FLOW_RATE = 0.75
DEFAULT_HOSE_INITIAL_WATER = DEFAULT_HOSE_CAPACITY
MIN_WATER_LEVEL = 0.0
HOSE_EQUALIZATION_DIVISOR = 2.0

DEFAULT_SPIGOT_FLOW_RATE = 1.0

DEFAULT_PLANT_NAME = "Plant"
DEFAULT_MATURITY_DAYS = 75
MIN_MATURITY_DAYS = 1
MISSING_MATURITY_DAYS = 0
DEFAULT_PLANT_WATER_CONSUMPTION = 0.05
DEFAULT_PLANT_GROWTH_RATE = 0.02
DEFAULT_PLANT_MAX_HEALTH = 100.0
DEFAULT_PLANT_HEALTH = DEFAULT_PLANT_MAX_HEALTH
DEFAULT_PLANT_VITALITY = 100.0
DEFAULT_PLANT_FERTILIZER = 1.0
DEFAULT_GROWTH_TICK_DAYS = 1.0
MIN_PLANT_FERTILIZER = 0.0
MIN_PLANT_MAX_HEALTH = 1.0
MIN_PLANT_VITALITY = 0.0
MIN_GROWTH_PROGRESS = 0.0
MAX_GROWTH_PROGRESS = 100.0
GROWTH_STATE_SEED = "SEED"
GROWTH_STATE_SPROUT = "SPROUT"
GROWTH_STATE_MATURE = "MATURE"
GROWTH_STATE_FRUITING = "FRUITING"
GROWTH_STATE_DEAD = "DEAD"
PLANT_STATES = (
    GROWTH_STATE_SEED,
    GROWTH_STATE_SPROUT,
    GROWTH_STATE_MATURE,
    GROWTH_STATE_FRUITING,
    GROWTH_STATE_DEAD,
)
GROWTH_SPROUT_THRESHOLD = 10.0
GROWTH_MATURE_THRESHOLD = 50.0
GROWTH_FRUITING_THRESHOLD = MAX_GROWTH_PROGRESS
PLANT_VISUAL_SPROUT_THRESHOLD = 10.0
PLANT_VISUAL_MATURE_THRESHOLD = 50.0
PLANT_VISUAL_FRUIT_THRESHOLD = MAX_GROWTH_PROGRESS
PLANT_VISUAL_STAGE_SEED = "seed"
PLANT_VISUAL_STAGE_SPROUT = "sprout"
PLANT_VISUAL_STAGE_MATURE = "mature"
PLANT_VISUAL_STAGE_FRUIT = "fruit"
PLANT_VISUAL_STAGE_WITHERED = "withered"

HEALTH_DECAY_PER_DRY_TICK = 0.10
HEALTH_RECOVERY_PER_WET_TICK = 0.05
VITALITY_DECAY_PER_DRY_TICK = 0.06
VITALITY_RECOVERY_PER_WET_TICK = 0.03
HEALTH_DEAD_THRESHOLD = 0.0

OFFLINE_CATCHUP_MAX_TICKS = 7 * 24 * 60 * 60
